spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
server:
  port: 8888
jwt:
  secret: 123123
  issuer: com.example.term
  expiration: 36000000
  prefix: "Bearer "

